package notionapi

// Code generated by notion.codegen; DO NOT EDIT.

// https://developers.notion.com/reference/property-value-object

// Each page property value object contains the following keys. In addition, it contains a key corresponding with the value of type. The value is an object containing type-specific data. The type-specific data are described in the sections below.
type PropertyValue struct {
	ID   string `json:"id"`             // Underlying identifier for the property. This identifier is guaranteed to remain constant when the property name changes. It may be a UUID, but is often a short random string.The id may be used in place of name when creating or updating pages.
	Type string `json:"type,omitempty"` // Type of the property. Possible values are "rich_text", "number", "select", "multi_select", "status", "date", "formula", "relation", "rollup", "title", "people", "files", "checkbox", "url", "email", "phone_number", "created_time", "created_by", "last_edited_time", and "last_edited_by".
	// Title property values: Title property value objects contain an array of rich text objects within the title property.
	// Rich Text property values: Rich Text property value objects contain an array of rich text objects within the rich_text property.
	// Number property values: Number property value objects contain a number within the number property.
	// Select property values: Select property value objects contain the following data within the select property:
	// Status property values: Status property value objects contain the following data within the status property:
	// Multi-select property values: Multi-select property value objects contain an array of multi-select option values within the multi_select property.
	// Multi-select option values:
	// Date property values: Date property value objects contain the following data within the date property:
	/*
	   Formula property values: Formula property value objects represent the result of evaluating a formula described in the
	   database's properties. These objects contain a type key and a key corresponding with the value of type. The value of a formula cannot be updated directly.
	   🚧Formula values may not match the Notion UI.Formulas returned in page objects are subject to a 25 page reference limitation. The Retrieve a page property endpoint should be used to get an accurate formula value.
	*/
	// String formula property values: String formula property values contain an optional string within the string property.
	// Number formula property values: Number formula property values contain an optional number within the number property.
	// Boolean formula property values: Boolean formula property values contain a boolean within the boolean property.
	// Date formula property values: Date formula property values contain an optional date property value within the date property.
	// Relation property values: Relation property value objects contain an array of page references within the relation property. A page reference is an object with an id property, with a string value (UUIDv4) corresponding to a page ID in another database. Updating with an empty array will clear the list. Note: a relation property has a maximum of 100 pages.
	/*
	   Rollup property values: Rollup property value objects represent the result of evaluating a rollup described in the
	   database's properties. These objects contain a type key and a key corresponding with the value of type. The value of a rollup cannot be updated directly.
	   🚧Rollup values may not match the Notion UI.Rollups returned in page objects are subject to a 25 page reference limitation. The Retrieve a page property endpoint should be used to get an accurate formula value.
	*/
	// String rollup property values: String rollup property values contain an optional string within the string property.
	// Number rollup property values: Number rollup property values contain a number within the number property.
	// Date rollup property values: Date rollup property values contain a date property value within the date property.
	// Array rollup property values: Array rollup property values contain an array of number, date, or string objects within the results property.
	// People property values: People property value objects contain an array of user objects within the people property.
	/*
	   Files property values: File property value objects contain an array of file references within the files property. A file reference is an object with a File Object and name property, with a string value corresponding to a filename of the original file upload (i.e. "Whole_Earth_Catalog.jpg").
	   📘When updating a file property, the value will be overwritten by the array of files passed.Although we do not support uploading files, if you pass a file object containing a file hosted by Notion, it will remain one of the files. To remove any file, just do not pass it in the update response.
	*/
	// Checkbox property values: Checkbox property value objects contain a boolean within the checkbox property.
	// URL property values: URL property value objects contain a non-empty string within the url property. The string describes a web address (i.e. "http://worrydream.com/EarlyHistoryOfSmalltalk/").
	// Email property values: Email property value objects contain a string within the email property. The string describes an email address (i.e. "[email protected]").
	// Phone number property values: Phone number property value objects contain a string within the phone_number property. No structure is enforced.
	// Created time property values: Created time property value objects contain a string within the created_time property. The string contains the date and time when this page was created. It is formatted as an ISO 8601 date time string (i.e. "2020-03-17T19:10:04.968Z"). The value of created_time cannot be updated. See the Property Item Object to see how these values are returned.
	// Created by property values: Created by property value objects contain a user object within the created_by property. The user object describes the user who created this page. The value of created_by cannot be updated. See the Property Item Object to see how these values are returned.
	// Last edited time property values: Last edited time property value objects contain a string within the last_edited_time property. The string contains the date and time when this page was last updated. It is formatted as an ISO 8601 date time string (i.e. "2020-03-17T19:10:04.968Z"). The value of last_edited_time cannot be updated. See the Property Item Object to see how these values are returned.
	// Last edited by property values: Last edited by property value objects contain a user object within the last_edited_by property. The user object describes the user who last updated this page. The value of last_edited_by cannot be updated. See the Property Item Object to see how these values are returned.
}
