package notionapi

// Code generated by notion.codegen; DO NOT EDIT.

// https://developers.notion.com/reference/emoji-object

// Emoji objects contain emoji data for page icons.
type Emoji struct {
	Type  string `json:"type"`  // Type of page icon. Possible values are: "emoji".
	Emoji string `json:"emoji"` // Emoji character.
}
