package notionapi

// Code generated by notion.codegen; DO NOT EDIT.

// https://developers.notion.com/reference/post-database-query-sort

// Sort object
//
// Property value sort
/*
This sort orders the database query by a particular property.
The sort object must contain the following properties:
*/
// Entry timestamp sort
/*
This sort orders the database query by the timestamp associated with a database entry.
The sort object must contain the following properties:
*/
