package notionapi

// Code generated by notion.codegen; DO NOT EDIT.

// https://developers.notion.com/reference/parent-object

// Pages, databases, and blocks are either located inside other pages, databases, and blocks, or are located at the top level of a workspace. This location is known as the "parent". Parent information is represented by a consistent parent object throughout the API.
type Parent struct {
	Type       string     `json:"type"`
	DatabaseID UUIDString `json:"database_id,omitempty"` // The ID of the database that this page belongs to.
	PageID     UUIDString `json:"page_id,omitempty"`     // The ID of the page that this page belongs to.
	Workspace  bool       `json:"workspace,omitempty"`   // Always true.
	BlockID    UUIDString `json:"block_id,omitempty"`    // The ID of the page that this page belongs to.
}
