package notionapi

// Code generated by notion.codegen; DO NOT EDIT.

// https://developers.notion.com/reference/database

// 📘Properties marked with an * are available to integrations with any capabilities. Other properties require read content capabilities in order to be returned from the Notion API. For more information on integration capabilities, see the capabilities guide.
type Database struct {
	Object         string              `json:"object"`           // Always "database".
	ID             UUIDString          `json:"id"`               // Unique identifier for the database.
	CreatedTime    ISO8601String       `json:"created_time"`     // Date and time when this database was created. Formatted as an ISO 8601 date time string.
	CreatedBy      *User               `json:"created_by"`       // User who created the database.
	LastEditedTime ISO8601String       `json:"last_edited_time"` // Date and time when this database was updated. Formatted as an ISO 8601 date time string.
	LastEditedBy   *User               `json:"last_edited_by"`   // User who last edited the database.
	Title          []RichText          `json:"title"`            // Name of the database as it appears in Notion. See rich text object) for a breakdown of the properties.
	Description    []RichText          `json:"description"`      // Description of the database as it appears in Notion. See rich text object) for a breakdown of the properties.
	Icon           *FileOrEmoji        `json:"icon"`             // Page icon.
	Cover          *File               `json:"cover"`            // Page cover image.
	Properties     map[string]Property `json:"properties"`       // Schema of properties for the database as they appear in Notion.key string The name of the property as it appears in Notion.value object A Property object.
	Parent         *Parent             `json:"parent"`           // Information about the database's parent. See Parent object.
	URL            string              `json:"url"`              // The URL of the Notion database.
	Archived       bool                `json:"archived"`         // The archived status of the  database.
	IsInline       bool                `json:"is_inline"`        // Has the value true if the database appears in the page as an inline block. Otherwise has the value false if the database appears as a child page.
}
